[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pipecore"
version = "0.1.0"
requires-python = ">=3.11"

[project.optional-dependencies]
dev = [
    "ruff",
    "mypy",
    "pytest",
]

[tool.ruff]
line-length = 999
[tool.ruff.lint]
ignore = [
    "BLE001",
    "SIM102",
]

[tool.mypy]
strict = true

[tool.pytest.ini_options]
testpaths = ["tests"]